# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title/
relative_permalinks: true

# Setup
title:            powdahound
tagline:          Dreaming of snow.
description:      Nerd on skis.
url:              http://powdahound.com
baseurl:          /
image_url:        /assets/

author:
  name:           'Garret Heaton'
  url:            https://twitter.com/powdahound

paginate:         3
