# Dependencies
markdown: kramdown
plugins: [jekyll-paginate]

# Permalinks
permalink:        /:year/:month/:title/

# Setup
title:            powdahound
tagline:          Dreaming of snow.
description:      Nerd on skis.
baseurl:          /
image_url:        /assets/

author:
  name:           'Garret Heaton'
  url:            https://twitter.com/powdahound

paginate:         3

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      author: "garret"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
